<#macro gridManager>
<section class="grid-manager-section grid-manager-bar">
  <div class="grid-manager-row">
    <span class="grid-manager-title">Grid Manager :</span>

    <div class="grid-manager-group">
      <span class="grid-manager-label">Columns :</span>
      <div class="gm-dropdown dropdown">
        <button type="button" id="columnsToggle" class="gm-toggle dropdown-toggle">
          Select Columns
        </button>
        <div class="gm-menu dropdown-menu" id="columnsMenu">
          <div class="gm-menu-header">
            <input type="text" id="columnsSearch" placeholder="Search columns" />
          </div>
          <div class="gm-menu-body" id="columnsMenuBody">
            <!-- Column checkboxes will be dynamically generated by grid-manager.js -->
          </div>
          <div class="gm-menu-footer">
            <button type="button" class="btn btn-primary" id="savePreferenceBtn" onclick="GridManager.savePreference()">
              Save Preferences
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="grid-manager-group">
      <span class="grid-manager-label">Preference :</span>
      <div class="gm-dropdown dropdown">
        <button type="button" id="preferenceToggle" class="gm-toggle dropdown-toggle">
          Select Preference
        </button>
        <div class="gm-menu dropdown-menu" id="preferenceMenu">
          <div class="gm-menu-body" id="preferenceList"></div>
          <div class="gm-menu-footer">
            <button type="button" class="btn btn-primary" id="applyPreferenceBtn" onclick="GridManager.applySelectedPreference()">
              Apply
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</#macro>

<#macro preferenceModal>
<!-- Preference Save Modal -->
<div id="preferenceModal" class="preference-modal">
  <div class="preference-modal-content">
    <div class="preference-modal-header">
      <h2>Save Column Preference</h2>
      <button type="button" class="preference-modal-close" onclick="GridManager.closePreferenceModal()">
        <i class="fas fa-times"></i>
      </button>
    </div>

    <div class="preference-modal-body">
      <div class="preference-option">
        <label class="preference-option-label">
          <input type="radio" name="preferenceType" value="suggested" checked onchange="GridManager.handlePreferenceTypeChange(this)" />
          <span>Save with suggested name</span>
        </label>
        <div class="preference-option-content">
          <div class="preference-suggestions">
            <span>Suggestions:</span>
            <div class="suggestion-list">
              <a href="#" class="suggestion-link" onclick="document.getElementById('suggestedPreferenceName').value='Preference 1'; event.preventDefault();">Preference 1</a>
              <a href="#" class="suggestion-link" onclick="document.getElementById('suggestedPreferenceName').value='Preference 2'; event.preventDefault();">Preference 2</a>
              <a href="#" class="suggestion-link" onclick="document.getElementById('suggestedPreferenceName').value='Preference 3'; event.preventDefault();">Preference 3</a>
            </div>
          </div>
          <input type="text" id="suggestedPreferenceName" class="preference-input" placeholder="Selected preference name will appear here" readonly />
        </div>
      </div>

      <div class="preference-option">
        <label class="preference-option-label">
          <input type="radio" name="preferenceType" value="custom" onchange="GridManager.handlePreferenceTypeChange(this)" />
          <span>Save custom name</span>
        </label>
        <div class="preference-option-content">
          <input type="text" id="customPreferenceName" class="preference-input" placeholder="Enter custom preference name" disabled />
        </div>
      </div>
    </div>

    <div class="preference-modal-footer">
      <button type="button" class="btn btn-cancel" onclick="GridManager.closePreferenceModal()">
        Cancel
      </button>
      <button type="button" class="btn btn-save-preference" onclick="GridManager.savePreferenceFromModal()">
        Save Preference
      </button>
    </div>
  </div>
</div>

<div id="successModal" class="success-modal">
  <div class="success-modal-content">
    <div class="success-icon">
      <i class="fas fa-check"></i>
    </div>
    <div class="success-message">Preference saved successfully!</div>
    <button type="button" class="btn btn-primary" onclick="GridManager.closeSuccessModal()" style="margin-top: 20px;">
      OK
    </button>
  </div>
</div>

<div id="appliedSuccessModal" class="success-modal">
  <div class="success-modal-content">
    <div class="success-icon">
      <i class="fas fa-check"></i>
    </div>
    <div class="success-message">Preference applied successfully!</div>
    <button type="button" class="btn btn-primary" onclick="GridManager.closeAppliedSuccessModal()" style="margin-top: 20px;">
      OK
    </button>
  </div>
</div>
</#macro>